export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_FILTER_PRODUCTS_REQUEST = "GET_FILTER_PRODUCTS_REQUEST";
export const GET_FILTER_PRODUCTS_SUCCESS = "GET_FILTER_PRODUCTS_SUCCESS";
export const GET_FILTER_PRODUCTS_FAILURE = "GET_FILTER_PRODUCTS_FAILURE";
